digitalocean/ceph_exporter

.travis.yml, README.md
- In-repo tests should run and pass before merging a PR.
- Included reference to godoc.
cc: @nickvanw @cagedmantis
=> Integrate Travis, Godoc

collectors/health.go, collectors/health_test.go
- New metrics are added for tracking total no. of OSDs and their state for e.g. IN, UP, etc.
- The count of PGs being moved around is surfaced.
- Comments are added for all the health types.
cc: @cagedmantis @mdlayher @nickvanw
=> Adds new OSD metrics

collectors/cluster_usage.go, collectors/cluster_usage_test.go, collectors/pool_usage.go, collectors/pool_usage_test.go
* Adds testing for extraneous and invalid cases.
cc: @mdlayher @cagedmantis
=> Testing improvements to cluster and pool stats.

Makefile.COMMON
=> Update to latest version of Makefile.COMMON

collectors/health.go, collectors/health_test.go
=> collectors/health: include a definitive ceph health check

collectors/health.go, collectors/health_test.go
We never surfaced the stats for stuck placement groups in past. This should fix that.
cc: @mdlayher @cagedmantis
=> health/pg_stats: stuck pg stats should be reported too

collectors/health.go, collectors/health_test.go
=> health/pgs: track misplaced objects from their pgs

README.md
Fixes https://github.com/digitalocean/ceph_exporter/issues/28.
=> readme: add a note about testing with ceph versions

.travis.yml, Dockerfile
=> ci: add ability to push to registry on success

README.md
Update the README to include a link to the dockerhub image.
r: @mdlayher
=> readme: add link to image on dockerhub

collectors/health.go, collectors/health_test.go
Slow requests information can be extracted from summary section
Fixes: https://github.com/digitalocean/ceph_exporter/issues/22
=> health: add slow requests

Dockerfile
A small update to the Dockerfile to support the new multi-stage builds
- Reduces the image size down to around 60MB
- Bumps up the base image to 16.04
=> Dockerfile with multi-stage build

collectors/monitors.go, collectors/monitors_test.go
Luminous dropped displaying skew and latency values in the `ceph status` command in Luminous. The skew and latency values for MONs are were moved to `time-sync-status`. This factors in that change to surface those values correctly for Luminous clusters.
r: @anthonyeleven
=> monitors: add back clock skew and latency metric support

README.md
=> Update README.md to add additional flags

collectors/health.go, collectors/health_test.go
I would like to export the OSD cluster map flags as metrics for monitoring and alerting.
=> Export OSD cluster map flags

collectors/pool.go, collectors/pool_test.go, vendor/github.com/ceph/go-ceph/rados/conn.go, vendor/github.com/ceph/go-ceph/rados/ioctx.go, vendor/github.com/ceph/go-ceph/rados/rados.go, vendor/vendor.json
This adds pool information collector to not only check current values but also to alert upon if anything changes.
=> collectors: add pool info collector 

collectors/osd.go, collectors/osd_test.go
pretty strait forward.  Lets us track when osds transition a couple more important states.
=> Adds per osd tracking of nearfull,backfillfull, and full states

collectors/health.go, collectors/health_test.go
r: @neurodrone 
There are a few other missing but I'm not sure how they got reported in the health just yet
=> health: adds unclean PGs for luminous

collectors/health.go, collectors/health_test.go, collectors/monitors.go, collectors/pool_usage.go
Ports https://github.com/digitalocean/ceph_exporter/pull/140
=> [nautilus] Allows pg_state gauges to return to 0

collectors/conn.go, collectors/osd.go, collectors/osd_test.go
Adds:
device_class: Class of device (ssd, hdd, etc)
host: host the osd is on
rack: rack the osd is in
root: root of the osd tree
=> Add additional labels to all osd metrics

collectors/conn.go, collectors/osd.go, collectors/osd_test.go
Port over from https://github.com/digitalocean/ceph_exporter/pull/147 to Nautilus
=> Additional labels for osd metrics nautilus

collectors/conn.go, collectors/pool.go, collectors/pool_test.go
Added the expansion factor metric which will compute the multiplier for data expansion for EC clusters. Will return the pool size if it is not an EC pool
=> CEPH-114 Added expansion_factor metric

collectors/health.go, collectors/health_test.go
This adds a gauge for incomplete PGs.
=> Add gauge for incomplete PGs

exporter.go
Forward-port of https://github.com/digitalocean/ceph_exporter/pull/132.
=> osd: set default timeout 30 seconds for Mon/OSD ops

collectors/conn.go, collectors/pool_usage.go
Nautilus counterpart for https://github.com/digitalocean/ceph_exporter/pull/171
=> nautilus: add pool metric unfound_objects_total

.travis.yml, collectors/conn.go, collectors/osd.go, collectors/osd_test.go, mocks/Conn.go
This is an attempt to fix the OSD collector hang issue observed in nautilus.
Ref: https://github.com/ceph/ceph/blob/master/src/mgr/MgrCommands.h
=> Use MgrCommand for "osd df", "osd perf" and "pg dump pgs_brief"

collectors/health.go, collectors/health_test.go
When a monitor is down, it should be urgent to notice administrator.
Signed-off-by: shminjs <shminjs@outlook.com>
=> Add new gauge to show the count of mon in down state.

collectors/health.go, collectors/health_test.go
=> collectors/health: add repair state checking

.github/workflows/run_build.yml, .github/workflows/run_tests.yml, Dockerfile, go.mod
Also build go-ceph targeting pacific. Tested against nautilus and pacific with no issues observed. :)
=> update Go to 1.18 and Docker image to focal

ceph/health.go
Misplaced ratio equals to misplaced_objects deviding misplaced_total, not misplaced_objects / num_objects.
So add a separate metric to show misplaced ratio.
Signed-off-by: haoyixing <haoyixing@kuaishou.com>
=> feat: add misplaced ratio metric

.github/workflows/run_build.yml, .github/workflows/run_tests.yml
=> Update Github Actions to use ubuntu 20.04

ceph/health.go
Removes the need for having special cases (eg. snaptrim) by splitting states using the `+` delimiter.
=> Split cluster health state by plus sign

METRICS.md, README.md
Was hoping for an auto doc generation ability but didn't find it so manual addition for now during which i found we exporter some old stuff from monitors we should really remove
Fixes #229
=> doc: add metrics list and desc

.github/workflows/build_and_push.yml
- Add job to push to docker tagged release
Fixes #236
=> gha: add build/push on tag update

ceph/osd.go
Without this, the granularity of the oldest active PG is based on external scrape frequency, and an unlucky sequence of scrapes could see the same PG inactive two scrapes in a row even though it was active in between.
Preferably, we would update this even more often than 10 seconds, but PG dumps can take a while.
=> osd: Internally poll PG dump for oldest active PG tracking

ceph/exporter.go, ceph/osd.go, ceph/osd_test.go
scrape created_at, ceph_version_when_created, and osd_objectstore from ceph osd metadata
=> osd: Add new collector for osd metadata

rados/rados.go
For now, this appears to be limited to read balancer fields, which show up in OSD dumps and pool details.
=> rados: Handle commands that return 'inf' as a float value

README.md
Adding note about it being in use against Reef.
=> readme: branch name cleanup
