digitalocean/ceph_exporter

- Dockerfile
- README.md
- This should start ceph exporter on `9190` port as a default. It can be changed later if need be.
cc: @nickvanw @mdlayher @cagedmantis
> Add docker integration

- Dockerfile
- README.md
- exporter.go
Picking the next available port as per https://github.com/prometheus/prometheus/wiki/Default-port-allocations instead of an arbitrary one.
r: @mdlayher @cagedmantis
> Pick a default prometheus port for CephExporter

- collectors/health.go
- collectors/health_test.go
This adds 6 more stats to the ceph exporter. In most recent stable `hammer (v0.94.5)` both the client and recovery I/O is not present in the cluster status JSON. It's available only in the plain output. This adds a new function we use to scan through that status and extract relevant values.
---
r: @mdlayher @cagedmantis
> health: add client and recovery IO stats

- .travis.yml
- collectors/health.go
- collectors/health_test.go
Jewel displays read and write client IOPS separately as seen below:
```
cluster 1cf6c452-efe7-4a1f-80b6-a2506168b685
health HEALTH_OK
monmap e13: 3 mons at {mon01=10.123.1.1:6789/0,mon02=10.123.1.2:6789/0,mon03=10.123.1.3:6789/0}
election epoch 258, quorum 0,1,2 mon01,mon02,mon03
osdmap e76078: 100 osds: 100 up, 100 in
pgmap v5396704: 10000 pgs, 1 pools, 1719 GB data, 523 kobjects
3441 GB used, 146 TB / 150 TB avail
10000 active+clean
client io 2399 MB/s wr, 750 op/s rd, 38410 op/s wr
```
This adds support for that while maintaining backward compatibility for hammer and below. Fixes https://github.com/digitalocean/ceph_exporter/issues/15.
r: @nickvanw
> health: Add support for IO ceph status changes in Jewel

- Dockerfile
- collectors/health.go
- collectors/health_test.go
We had a collision with regex due to the new Jewel convention (`\w{2}` =~ `op` =~ `MB`) . The regex for extracting client B/W has been made much stricter now to adhere to this.
Additionally the test is modified so that this issue is more apparent by causing the test to fail without having any B/W values to bank on.
This should fix https://github.com/digitalocean/ceph_exporter/issues/17.
> health: Fix conflict of "ops/s" with bandwidth units

- Dockerfile
Build `ceph_exporter` docker bin against the latest version of Ceph: Jewel.
> docker: support building librados against ceph Jewel

- collectors/pool_usage.go
Since we need to use `Set()` for setting values for individual read and write metrics, we need to switch to using `Gauge` instead of `Counter`.
> pool: fix read/write counters

- collectors/health.go
- collectors/health_test.go
- cache flush and evict io rates
- cache promote iops
- I don't know why promote is only iops but flush and evict are data rates
- TODO: expose when the urgent eviction rate kicks in (I belive this shows up as (high) on the cache io line)
> health: expose metrics for cache tier pool operations

- collectors/health.go
- collectors/health_test.go
This adds in a way to get total PGs in the cluster without the need to do complex arithmetic. We also note that misplaced and degraded object count values include replica copies.
r: @mdlayher 
Fixes https://github.com/digitalocean/ceph_exporter/issues/36.
> health: add total pg count

- collectors/health.go
- collectors/health_test.go
Pull the OSD down values from the delta of total OSDs against the ones that are up, instead of reading this information from the summary.
r: @mdlayher 
Fixes https://github.com/digitalocean/ceph_exporter/issues/34.
> health: fix osd_down metric

- exporter.go
Hi,
On my ceph cluster, I have created a monitoring user with only read permission. I don't want to use admin user to execute monitoring tasks.
I have made a little modification in order to support passing user as a a parameter to ceph_exporter:
`-ceph.user <user>`
ceph_exporter will look into ceph conf directory for a key file named `ceph.client.<user>.keyring`
> Support ceph user other than admin

- .travis.yml
- Dockerfile
This fixes the issue with the installation of librados and librbd Jewel libraries. It also adds docker tags that identifies each release separately. In future we should change it to release versions once we decide on how releases should look like.
r: @mdlayher 
Fixes https://github.com/digitalocean/ceph_exporter/issues/42.
> bug: fix installation of ceph libraries, add docker tags

- .travis.yml
- exporter.go
This changes docker image builds to only happen on tagged releases. Also adds a status page to root path.
> travis: fix docker push, add default page

- collectors/osd.go
- collectors/osd_test.go
Due to http://tracker.ceph.com/issues/18239 Ceph will generate invalid
json output when there is any of OSD out of the cluster. Since it is
invalid, golang is unable to unmarshal the json and can result in
confusing metrics. Replacing -nan to 0 is certainly a workaround,
but this can temporarily prevent wrong metrics.
Fix issue: https://github.com/digitalocean/ceph_exporter/issues/48
> Fix parsing invalid json produced by Ceph after 10.2.5 when OSD is out

- collectors/health.go
- collectors/health_test.go
Parse pg statuses from ceph status and sum up the numbers of pgs
that have "scrubbing" or "scrubbing+deep" state name.
Fixes: https://github.com/digitalocean/ceph_exporter/issues/22
> health: add scrubbing and deep-scrubbing pgs

- collectors/pool_usage.go
If there's no pools created yet (which can be true after a ceph
cluster is initially created, but before any pools are present),
there'll be a log every minute "[ERROR] failed collecting pool
usage metrics: no pools found in the cluster to report stats on".
IMO that's not actually an error, it's just the way things are,
so doesn't really need to be reported.
Signed-off-by: Tim Serong <tserong@suse.com>
> pool: remove error log when no pools present

- collectors/health.go
- collectors/health_test.go
Extract slow request information from health checks in ceph luminous. It's still compatible to older versions of ceph.
It's possible to add additional luminous metrics, i.e. stucked pgs, in the same way.
> health: expose slow requests for luminous

- collectors/health.go
- collectors/health_test.go
An update to ceph luminous breaks the metrics for recovery and client io, because of the new output format for ceph status.
The updates are still compatible to older versions of ceph.
note: not my change but fixes one of my luminous upgrade problems
> health: expose client io and recovery io for luminous

- exporter.go
Why this change is necessary?
This commit resolves issue #68 .
How will this change affect to the project?
[Prometheus](prometheus.io) has clearly mentioned in their code that this method is deprecated, use `promhttp.Handler()` instead. This is very similar to `prometheus.Handler()`. This will not have any major impact on the project.
> update /metrics handler to promhttp.Handler()

- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
- vendor/vendor.json
This adds promhttp (required by 4c70969) to the vendor directory.
Signed-off-by: Tim Serong <tserong@suse.com>
> Add promhttp to vendor directory

- Dockerfile
- collectors/health.go
- collectors/health_test.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
- vendor/vendor.json
This change makes improvements within the exporter to scrape PG stats among others that were only done for Jewel clusters earlier. Going forward we won't rely on plaintext stats anymore.
Go is bumped to the latest version that works without issues while building the exporter.
We still do not extract the clock skew / latency stats since that information was moved away from monmap. A separate PR should be able to address that.
r: @ssobolewski
> luminous: move health stats to be extracted from status json

- exporter.go
This is somewhat of a workaround for the exporter becoming
perpetually blocked when it runs out of file descriptors if
the cluster is down for too long, as mentioned in:
https://github.com/digitalocean/ceph_exporter/issues/60#issuecomment-319396108
The problem is that if the MONs are down for long enough,
each time prometheus scrapes the metrics, another socket is
opened, but these block forever.  If the cluster comes back
up before we run out of FDs, the blocked requests recover.
If the clusetr *doesn't* come back up before we run out of
FDs, the blocked requests never recover.
This commit causes ceph exporter to terminate if it runs
out of file descriptors, which IMO is better than blocking
forever -- it'll be a noisier failure, and also if you're
running ceph_exporter via systemd, …
> Terminate exporter process if maximum open files exceeded

- .travis.yml
- Dockerfile
- collectors/health.go
- collectors/health_test.go
This adds in functionality to track slow requests per OSD. If slow requests exist on multiple OSD they will show up too. Currently Ceph displays no breakdown if multiple OSDs exhibit slow request in same time interval, which complicates our efforts to find accurate value. We assume the worst case in such a situation and count max no. of slow requests for each such OSD. This change keeps the older `slow_requests` stat for backwards compatibility since we don't want the stat to simply vanish if people have built tooling or alerting around it.
> health: capture slow request per osd

- collectors/health.go
- collectors/health_test.go
We should also capture blocked requests that occur for an OSD categorized under `REQUEST_STUCK`. 
r: @ssobolewski
> health: add visibility for stuck requests

- collectors/osd.go
- collectors/osd_test.go
Track if there is an ongoing scrub to a PG on a given OSD. This should help with correlating slow requests to active scrubs.
> Add tracking of scrub/deep scrub on a per osd basis

- collectors/osd.go
- collectors/osd_test.go
We should now able to see (and alert on) OSDs when they are `down` or `destroyed`. Those are the only two types today but the change is kept flexible to accommodate any new types that might be added in future.
r: @anthonyeleven
> osd: add metrics for down and destroyed OSD

- collectors/health.go
- collectors/health_test.go
This metric allows to graph active PGs vs not active, i.e. the number of
PGs ceph is serving vs. currently unavailable PGs.
Signed-off-by: Jan Fajerski <jfajerski@suse.com>
> health: add active_pg metric

- Dockerfile
- collectors/rgw.go
- collectors/rgw_test.go
- exporter.go
Simple exporter to collect RGW GC stats to see if we are being flooded or backlogged with GC operations.
> Optionally collect RGW GC task stats

- collectors/monitors.go
- collectors/osd.go
- collectors/pool_usage.go
Signed-off-by: Jan Fajerski <jfajerski@suse.com>
Fixes #102
> collectors: Reset metric vectors; pools and daemons can vanish

- collectors/health.go
- collectors/health_test.go
The degraded and misplaced object stats were showing incorrectly as 0 because they were not being picked up properly from new checks that went into luminous. This attempts at fixing that issue.
r: @robbat2 @ralfonso
> health: fix degraded/misplaced object count

- collectors/health.go
- collectors/health_test.go
This change adds stats for PGs under recovering and backfill state to our exporter.
r: @ssobolewski
> luminous: add recovery/backfill stats

- exporter.go
Register the `PoolInfoCollector` with generic Ceph exporter runs.
r: @alram
> exporter: register pool info collector

- collectors/health.go
- collectors/health_test.go
This change adds "stuck_requests" metric to ceph exporter so we can track those separately to slow requests.
r: @alram
> collector/health: add stuck request metric

- collectors/health.go
- exporter.go
Fixing failed builds due to errors in the struct being passed for health warning map.
> Exporter: Type errors

- collectors/osd.go
- collectors/osd_test.go
With Ceph Nautilus release, The output of this command `ceph osd perf --format json` is different with luminous/mimic.
WIth this PR, I have changed the struct to unmarshal the data. Please create a new branch `nautilus`. 
Thank you.
> Support OSD Latency for Nautilus release

- collectors/conn.go
- collectors/osd.go
- collectors/osd_test.go
- vendor/github.com/ceph/go-ceph/rados/conn.go
This PR includes below changes
* Make ceph-go able to send PG command in order to run `ceph tell PGID query`
* Add a new counter metric `ceph_pg_objects_recovered_total` to collect the number of objects recovered in a PG
* Refactoring for `NoopConn` so that it can mock Ceph command output based on input. Also, after this refactoring, when running `go test`, it is possible to run multiple Ceph commands in a single scrape.
* Refactoring for `OSDCollector` because of above
r @neurodrone @ssobolewski
> Add ability to collect PG recovery rate

- collectors/osd.go
- collectors/osd_test.go
It is found that `ceph_pg_objects_recovered_total` does not show up unless there is a PG in recovering state. In order to make it available even if no PG is recovering, update it for every scrape.
> osd: update ceph_pg_objects_recovered_total in every scrape

- collectors/osd.go
- collectors/osd_test.go
PG query provides the absolute value for number of objects recovered. It would be much easier to use a Gauge for this metric.
> osd: use gauge for ceph_pg_objects_recovered

- Dockerfile
@neurodrone 
Not sure how CI passed previously but the nautilus docker image won't build without this
> nautilus: fix docker build

- .travis.yml
- Dockerfile
- Makefile.COMMON
- collectors/conn.go
- collectors/osd.go
- collectors/osd_test.go
This PR includes below changes:
* Add a counter for number of objects backfilled for an OSD
* Add support for `NoopConn` to have multiple iterations with commands / expected outputs.
> osd: add a counter for number of objects backfilled on each OSD

- exporter.go
It's found that `PGCommand` may hang when issuing PG query if the PG is in some intermediate states. To prevent it from hanging there set `rados_osd_op_timeout` and `rados_mon_op_timeout` for `go-ceph` only.
r @neurodrone
> osd: set default timeout 30 seconds for Mon/OSD ops

- .travis.yml
- Dockerfile
- Makefile.COMMON
- collectors/cluster_usage.go
- collectors/cluster_usage_test.go
- collectors/health.go
- collectors/health_test.go
cluster_objects was collected from output of the ceph df detail command in luminous. In nautilus, the output no longer contains the total_objects stat. For nautilus, the cluster_objects metric will be collected using ceph health command, which returns the num_objects stat.
> Metric Fix: cluster_objects

- collectors/conn.go
- collectors/osd.go
- collectors/osd_test.go
- vendor/github.com/ceph/go-ceph/rados/conn.go
Modified struct for pg dump pgs_brief command, due to changes in the command output
Fixed - pg_objects_recovered, osd_scrub_state, and osd recovery rate
Added pg query functionality that was added into luminous branch (by @yuezhu ) - which also involved the modifying of a vendor file, since the upstream PR has not been merged yet.
> Fixing Metrics due to Nautilus command output changes

- collectors/health.go
- collectors/health_test.go
Due to Nautilus replacing REQUEST_STUCK and REQUEST_SLOW with SLOW_OPS, and changing the output, the metrics and collector needed to be modified to account for this. 
The new output for slow ops also states the time for the "oldest" slow op. It may not be accurate to assume all osd's listed can be associated with that one time, so the slow_requests_osd metric is removed.
> replacing slow requests and stuck requests metrics with slow ops metrics

- collectors/osd.go
- collectors/osd_test.go
fixes: https://github.com/digitalocean/ceph_exporter/issues/136 
OSD perf metrics are not reported with luminous.
> restore 1f2df8db38b2a400758ef37ed2a531965ee120fe

- collectors/health.go
- collectors/health_test.go
- collectors/monitors.go
- collectors/pool_usage.go
This does change the default behaviour for these metrics. Previously, these time series did not exist until ceph_exporter observed a pg in the given state. Now these time series will always exist and be zero whenever ceph_exporter sees no pgs in the given state.
Also run `go fmt`, because we're not animals. :heart:
> Allows pg_state gauges to return to 0

- collectors/pool.go
With Luminous, the erasure-code-profile value for a replicated pool
was the CRUSH rule name. With Nautilus erasure-code-profile is empty
for a replicated pool, so we check for the pool type and if the pool
is replicated we set its profile
> pool: override profile on Nautilus replicated pools

- collectors/pool_usage.go
- collectors/pool_usage_test.go
According to https://docs.ceph.com/docs/master/releases/nautilus/:
```
‘raw bytes used’ column renamed to “stored_raw”. Totals of user data
over all OSD excluding degraded.
```
Updating the internal metric accordingly.
> fix renamed in Nautilus metric

- collectors/health.go
- collectors/health_test.go
- collectors/pool_usage.go
- collectors/pool_usage_test.go
The Ceph upstream PR that changed around the raw/used stats also introduced a per-pool percent used metric in the range [0-1]. This PR exposes that metric and makes minor tweaks to a comment and a help string.
I also found that `ceph_mgrs` and `ceph_mgrs_active` were missing, so I copied them over from the `luminous` branch too.
Tested against ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable)
@alram This is against the `nautilus` branch.
> Capture new percent_used pool metric and copy over mgr metrics from the Luminous branch

- collectors/pool_usage.go
- collectors/pool_usage_test.go
bytes_used went from object-bytes-used (thus raw/expansion) in Luminous to raw-bytes-used in Nautilus. The new stored value is the closest thing to the previous bytes_used.
> pool_usage: Fix the used-bytes metric for Nautilus.

- collectors/conn.go
- collectors/pool.go
We had assumed that the "take" step came first, but that's not necessarily the case.
> [luminous] pool: Eliminate bad assumption about crush rule ordering.

- collectors/conn.go
- collectors/pool.go
We had assumed that the "take" step came first, but that's not necessarily the case.
> [nautilus] pool: Eliminate bad assumption about crush rule ordering.

- collectors/conn.go
- collectors/pool_usage.go
This adds a per-pool metric `unfound_objects_total` for luminous branch.
> luminous: add pool metric unfound_objects_total

- collectors/osd.go
- collectors/osd_test.go
Add new gauge to show osd full/nearfull/backfillfull ratio.
Not only do we need to know whether a osd is full or not, we
also want to know the exact full ratio was for a cluster.
For many clusters which have different full ratio set, this
should be meaningfull.
Signed-off-by: haoyixing <haoyixing@kuaishou.com>
> feat: add osd full/nearfull/backfillfull ratio

- collectors/health.go
- collectors/health_test.go
Nautilus no longer reports misplaced objects as a health status, but it is available in the pgmap data. For consistency, let's get the degraded object count from there as well.
> collectors/health: Fix ceph_misplaced_objects on Nautilus.

- collectors/osd.go
Backporting the oldest PG inactive age metric to Luminous.
Ref: https://github.com/digitalocean/ceph_exporter/pull/195
> Luminous: Backport oldest PG inactive

- collectors/health.go
- collectors/health_test.go
Guess who has two and a half thumbs and didn't make tests for https://github.com/digitalocean/ceph_exporter/pull/198?  This guy!
Fixes a bug with snaptrim collection introduced due to `strings.Contains()` usage, where states are `snaptrim+foo`, which matches for both `snaptrim` and `snaptrim_wait`.
> collectors/health: fix snaptrim collection, add a test

- collectors/health.go
- collectors/health_test.go
Guess who has two and a half thumbs and didn't make tests for #198? This guy!
Fixes a bug with snaptrim collection introduced due to `strings.Contains()` usage, where states are `snaptrim+foo`, which matches for both `snaptrim` and `snaptrim_wait`.
> Luminous snaptrim fix

- ceph/crashes.go
- ceph/crashes_test.go
- ceph/exporter.go
New metric: `ceph_crash_reports` which counts the entries returned by `ceph crash ls` by daemon name and archival status.
This is not the same as `ceph_new_crash_reports` which is the value of the `RECENT_CRASH` health check, and that only counts the non-archived errors of the past two weeks. The new metric counts errors as long as they are not purged (which is done after 1 year by defaults).
> Implement new gauge for counting crash reports by daemon/status

- ceph/health.go
- ceph/health_test.go
- ceph/pool_usage.go
Switching the prometheus gauges to ConstMetrics will help address the issue of some metrics being at wrong values (eg. ceph_pg_state).
Addresses issue #102 
Not all gauges have been moved to ConstMetrics in health.go - the ones related to OSD mapping stayed as gauges. This is because existing logic and unit tests need them initialized at 0 and then updated based on certain flags, which is more difficult to do when using ConstMetrics.
> Replaces gauges with constmetrics

- .github/workflows/license.yml
Helps avoid changing this file every year. :) 
r: @digitalocean/storage
> github-actions/license: make license year future-proof

- main.go
- rados/rados.go
Establishes and maintains only 1 RADOS connection per cluster config. These changes have shown to result in a very noticeable decrease in resource consumption, particularly RAM and even CPU usage.
> rados: establish only 1 rados connection

- .github/workflows/license.yml
- .github/workflows/run_build.yml
- .github/workflows/run_tests.yml
- Dockerfile
- go.mod
- go.sum
- Update Go env from 1.18 to 1.20
> go: update envs to use go 1.20

- ceph/osd.go
- ceph/osd_test.go
- `ceph_osd_down` had it's rack/root labels swapped
- `ceph_osd_scrub_state` had rack label as root
> ceph/osd: fix root/rack labels

- main.go
Not instantiating an exporter and logging instead of failing to start when we can't connect to one of the configured clusters is not the behaviour we want; a user may think that ceph_exporter is monitoring all of the requested clusters (since it's up and responds to metrics requests) when in fact data is missing.
> Fail to start if any rados connection fails on startup
